name: "Publish to Zenodo"
description: "Publish a set of files to Zenodo"
inputs:
    files:
        description: "List of files or glob patterns to publish. Cannot include directories, so create a zip file if you need to include directories."
        required: true
    citation:
      description: "Path to CITATION.cff file, used to create `.zenodo.json` metadata file."
      required: true
      default: "CITATION.cff"
    sandbox:
        description: "If true, publish to Zenodo sandbox."
        required: false
        default: "true"
    publish:
        description: "Publish the record. If false, you'll need to go to Zenodo, review the record, and publish it manually."
        required: false
        default: "false"
    concept:
        description: "Create the deposition as a new version of this concept DOI (e.g. `12345678`)."
        required: false
        default: ''
    verbose:
        description: "Verbose output"
        required: false
        default: "false"

runs:
  using: "composite"
  steps:

    - name: Get file list
      uses: tj-actions/glob@v22
      id: globber
      with:
        files: ${{ inputs.files }}
        match-directories: false

    - name: Print the list of files
      run: echo "${{ steps.globber.outputs.paths }}"
      shell: bash

    - name: Create a zenodo metadata file from CITATION.cff
      uses: citation-file-format/cffconvert-github-action@2.0.0
      with:
        args: "-i ${{ inputs.citation }} -f zenodo -o .zenodo.json"

    - name: Create a draft snapshot of your repository figure content.
      uses: zenodraft/action@0.13.3
      with:
        concept: ${{ inputs.concept }}
        filenames: "${{ steps.globber.outputs.paths }}"
        metadata: .zenodo.json
        publish: ${{ inputs.publish }}
        sandbox: ${{ inputs.sandbox }}
        verbose: ${{ inputs.verbose }}
