name: "Publish to Zenodo"
description: "Publish a set of files to Zenodo."
inputs:
    files:
        description: "List of files or glob patterns to publish. Cannot include directories, so create a zip file if you need to include directories."
        required: true
    metadata:
      description: "Path to metadata YAML file, used to create `.zenodo.json` metadata file. Use Zenodo conventions."
      required: true
    sandbox:
        description: "If true, publish to Zenodo sandbox."
        required: false
        default: "true"
    publish:
        description: "Publish the record. If false, you'll need to go to Zenodo, review the record, and publish it manually."
        required: false
        default: "false"
    concept:
        description: "Create the deposition as a new version of this concept DOI (e.g. `12345678`)."
        required: false
        default: ''
    verbose:
        description: "Verbose output"
        required: false
        default: "false"

runs:
  using: "composite"
  steps:

    - name: Get file list
      uses: tj-actions/glob@v22
      id: globber
      with:
        files: ${{ inputs.files }}
        match-directories: false

    - name: Print the list of files
      run: echo "${{ steps.globber.outputs.paths }}"
      shell: bash

    - name: Validate metadata against Zenodo schema
      uses: GrantBirki/json-yaml-validate@v3.2.1
      with:
        comment: "true" # enable comment mode
        files: |
          ${{ inputs.metadata }}
        yaml_as_json: "true"
        json_schema:  "${{ github.action_path }}/schema/zenodo/0.3.0/schema.json"
        ajv_strict_mode: "false"

    - name: Convert metadata YAML to .zenodo.json
      uses: mikefarah/yq@master
      with:
        cmd: cat ${{ inputs.metadata }} | yq e -o=json - > .zenodo.json

    - name: Print zenodo metadata
      run: cat .zenodo.json
      shell: bash

    - name: Create a draft snapshot of your repository figure content.
      uses: zenodraft/action@0.13.3
      with:
        concept: ${{ inputs.concept }}
        filenames: "${{ steps.globber.outputs.paths }}"
        metadata: .zenodo.json
        publish: ${{ inputs.publish }}
        sandbox: ${{ inputs.sandbox }}
        verbose: ${{ inputs.verbose }}
